### PR TITLE
Latest upstream 7.2.19

### PR DESCRIPTION
**Pull request by vosscodes**
Latest upstream 7.2.19 (fixed date/tag)

### CODE REVIEW

**Comment by carlwgeorge** [comment]
Thank you!

**Comment by carlwgeorge** [comment]
I've published this update to the testing repo.

**Comment by snlnspc** [comment]
No issues testing on 600~ sites

**Comment by carlwgeorge** [comment]
Thanks for the testing @snlnspc, pushing this to stable now.

**Pull request merged**
