### PR TITLE
Update to PHP 7.2.28

### PR DESCRIPTION
**Pull request by milosz**
I have performed test buid:
```
Checking for unpackaged file(s): /usr/lib/rpm/check-files /root/rpmbuild/BUILDROOT/php72u-7.2.28-1.el7.x86_64
Wrote: /root/rpmbuild/SRPMS/php72u-7.2.28-1.el7.src.rpm
Wrote: /root/rpmbuild/RPMS/x86_64/mod_php72u-7.2.28-1.el7.x86_64.rpm
Wrote: /root/rpmbuild/RPMS/x86_64/php72u-cli-7.2.28-1.el7.x86_64.rpm
Wrote: /root/rpmbuild/RPMS/x86_64/php72u-dbg-7.2.28-1.el7.x86_64.rpm
Wrote: /root/rpmbuild/RPMS/x86_64/php72u-fpm-7.2.28-1.el7.x86_64.rpm
Wrote: /root/rpmbuild/RPMS/noarch/php72u-fpm-nginx-7.2.28-1.el7.noarch.rpm
Wrote: /root/rpmbuild/RPMS/noarch/php72u-fpm-httpd-7.2.28-1.el7.noarch.rpm
Wrote: /root/rpmbuild/RPMS/x86_64/php72u-common-7.2.28-1.el7.x86_64.rpm
Wrote: /root/rpmbuild/RPMS/x86_64/php72u-devel-7.2.28-1.el7.x86_64.rpm
Wrote: /root/rpmbuild/RPMS/x86_64/php72u-opcache-7.2.28-1.el7.x86_64.rpm
Wrote: /root/rpmbuild/RPMS/x86_64/php72u-imap-7.2.28-1.el7.x86_64.rpm
Wrote: /root/rpmbuild/RPMS/x86_64/php72u-ldap-7.2.28-1.el7.x86_64.rpm
Wrote: /root/rpmbuild/RPMS/x86_64/php72u-pdo-7.2.28-1.el7.x86_64.rpm
Wrote: /root/rpmbuild/RPMS/x86_64/php72u-mysqlnd-7.2.28-1.el7.x86_64.rpm
Wrote: /root/rpmbuild/RPMS/x86_64/php72u-pgsql-7.2.28-1.el7.x86_64.rpm
Wrote: /root/rpmbuild/RPMS/x86_64/php72u-process-7.2.28-1.el7.x86_64.rpm
Wrote: /root/rpmbuild/RPMS/x86_64/php72u-odbc-7.2.28-1.el7.x86_64.rpm
Wrote: /root/rpmbuild/RPMS/x86_64/php72u-soap-7.2.28-1.el7.x86_64.rpm
Wrote: /root/rpmbuild/RPMS/x86_64/php72u-interbase-7.2.28-1.el7.x86_64.rpm
Wrote: /root/rpmbuild/RPMS/x86_64/php72u-snmp-7.2.28-1.el7.x86_64.rpm
Wrote: /root/rpmbuild/RPMS/x86_64/php72u-xml-7.2.28-1.el7.x86_64.rpm
Wrote: /root/rpmbuild/RPMS/x86_64/php72u-xmlrpc-7.2.28-1.el7.x86_64.rpm
Wrote: /root/rpmbuild/RPMS/x86_64/php72u-mbstring-7.2.28-1.el7.x86_64.rpm
Wrote: /root/rpmbuild/RPMS/x86_64/php72u-gd-7.2.28-1.el7.x86_64.rpm
Wrote: /root/rpmbuild/RPMS/x86_64/php72u-bcmath-7.2.28-1.el7.x86_64.rpm
Wrote: /root/rpmbuild/RPMS/x86_64/php72u-gmp-7.2.28-1.el7.x86_64.rpm
Wrote: /root/rpmbuild/RPMS/x86_64/php72u-dba-7.2.28-1.el7.x86_64.rpm
Wrote: /root/rpmbuild/RPMS/x86_64/php72u-tidy-7.2.28-1.el7.x86_64.rpm
Wrote: /root/rpmbuild/RPMS/x86_64/php72u-pdo-dblib-7.2.28-1.el7.x86_64.rpm
Wrote: /root/rpmbuild/RPMS/x86_64/php72u-embedded-7.2.28-1.el7.x86_64.rpm
Wrote: /root/rpmbuild/RPMS/x86_64/php72u-pspell-7.2.28-1.el7.x86_64.rpm
Wrote: /root/rpmbuild/RPMS/x86_64/php72u-recode-7.2.28-1.el7.x86_64.rpm
Wrote: /root/rpmbuild/RPMS/x86_64/php72u-intl-7.2.28-1.el7.x86_64.rpm
Wrote: /root/rpmbuild/RPMS/x86_64/php72u-enchant-7.2.28-1.el7.x86_64.rpm
Wrote: /root/rpmbuild/RPMS/x86_64/php72u-json-7.2.28-1.el7.x86_64.rpm
Wrote: /root/rpmbuild/RPMS/x86_64/php72u-sodium-7.2.28-1.el7.x86_64.rpm
Wrote: /root/rpmbuild/RPMS/x86_64/php72u-debuginfo-7.2.28-1.el7.x86_64.rpm
Executing(%clean): /bin/sh -e /var/tmp/rpm-tmp.SVD5DY
+ umask 022
+ cd /root/rpmbuild/BUILD
+ cd php-7.2.28
+ /usr/bin/rm -rf /root/rpmbuild/BUILDROOT/php72u-7.2.28-1.el7.x86_64
+ exit 0
```

### CODE REVIEW

**Review by carlwgeorge — APPROVED** [review]

**Comment by carlwgeorge** [comment]
Thanks!  I've published 7.2.28-1 to the testing repository. Please try it out and if all looks well I'll be happy to promote that release to the main repository.

**Comment by milosz** [comment]
OK. Thanks.

**Comment by milosz** [comment]
I have tested it and it works as expected.
```
[staging ~]$ systemctl status php-fpm
● php-fpm.service - The PHP FastCGI Process Manager
   Loaded: loaded (/usr/lib/systemd/system/php-fpm.service; enabled; vendor preset: disabled)
   Active: active (running) since wto 2020-03-10 07:44:58 UTC; 18min ago
 Main PID: 27531 (php-fpm)
   Status: "Processes active: 1, idle: 9, Requests: 1512, slow: 0, Traffic: 0.9req/sec"
   Memory: 624.9M
   CGroup: /system.slice/php-fpm.service
           ├─27531 php-fpm: master process (/etc/php-fpm.conf)
           ├─27544 /usr/bin/newrelic-daemon ...
           ├─27555 php-fpm: pool www
           ├─27556 php-fpm: pool www
           ├─27557 php-fpm: pool www
           ├─27558 php-fpm: pool www
           ├─27559 php-fpm: pool www
           ├─27562 /usr/bin/newrelic-daemon ...
           ├─27784 php-fpm: pool www
           ├─28382 php-fpm: pool www
           ├─28384 php-fpm: pool www
           ├─28385 php-fpm: pool www
           └─28484 php-fpm: pool www
[staging ~]$ php -v
PHP 7.2.28 (cli) (built: Mar  9 2020 22:23:15) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.2.28, Copyright (c) 1999-2018, by Zend Technologies
```

**Comment by carlwgeorge** [comment]
I've pushed the build to the main repo.  Thanks again!

**Comment by milosz** [comment]
Thanks. I will update release tag (which was saved as a draft).

**Pull request merged**
